/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type OperationIdentityMeRequest = {
  path: {
    [k: string]: string | undefined;
  };
  query: {
    [k: string]: string | undefined;
  };
  cookie: {
    [k: string]: string | undefined;
  };
  header: {
    [k: string]: string | undefined;
  };
  authorizer: AuthorzierContextAuthorizer;
};
export type OperationIdentityMeResponses = {
  statusCode: 200;
  headers: {};
  body: {
    /**
     * indicates the status
     */
    ok: boolean;
    /**
     * indicates the username
     */
    user: string;
    [k: string]: unknown | undefined;
  };
};

export interface _ {
  AuthContext?: AuthContext;
  OperationIdentityMe?: OperationIdentityMe;
  OperationIdentityMeRequest?: OperationIdentityMeRequest;
  AuthorzierContextAuthorizer?: AuthorzierContextAuthorizer;
  OperationIdentityMeResponses?: OperationIdentityMeResponses;
}
export interface AuthContext {
  name: string;
}
export interface OperationIdentityMe {
  request: OperationIdentityMeRequest;
  responses: OperationIdentityMeResponses;
}
export interface AuthorzierContextAuthorizer {
  lambda: AuthContext;
  [k: string]: unknown | undefined;
}
