/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type OperationTestingRequest = {
  path: {
    [k: string]: string | undefined;
  };
  query: {
    [k: string]: string | undefined;
  };
  cookie: {
    [k: string]: string | undefined;
  };
  header: {
    [k: string]: string | undefined;
  };
  authorizer: AuthorzierContextAuthorizer;
};
export type OperationTestingResponses = {
  statusCode: 200;
  headers: {};
  body: {
    /**
     * indicates the status
     */
    ok: boolean;
    /**
     * indicates the username
     */
    user: string;
    [k: string]: unknown | undefined;
  };
};

export interface _ {
  AuthContext?: AuthContext;
  OperationTesting?: OperationTesting;
  OperationTestingRequest?: OperationTestingRequest;
  AuthorzierContextAuthorizer?: AuthorzierContextAuthorizer;
  OperationTestingResponses?: OperationTestingResponses;
}
export interface AuthContext {
  name: string;
}
export interface OperationTesting {
  request: OperationTestingRequest;
  responses: OperationTestingResponses;
}
export interface AuthorzierContextAuthorizer {
  lambda: AuthContext;
  [k: string]: unknown | undefined;
}
