/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type OperationTestRequest = {
  path: {
    [k: string]: string | undefined;
  };
  query: {
    [k: string]: string | undefined;
  };
  cookie: {
    [k: string]: string | undefined;
  };
  header: {
    [k: string]: string | undefined;
  };
  authorizer: AuthContext;
};
export type OperationTestResponses = {
  statusCode: 200;
  headers: {};
  body: {
    ok: boolean;
    [k: string]: unknown | undefined;
  };
};

export interface _ {
  AuthContext?: AuthContext;
  OperationTest?: OperationTest;
}
export interface AuthContext {
  name: string;
}
export interface OperationTest {
  request: OperationTestRequest;
  responses: OperationTestResponses;
}
