/**
 * ATTENTION: This file was generated by @cloudventure/sdf package
 * and it will be regenerated when the stack is synthesized.
 */

import { httpApiRuntime } from "@cloudventure/sdf";
import { OperationTesting as Operation } from "./../../interfaces";
import * as validators from "./validators/testing.validator";
import { handler } from "./../../../api/testing";

export type OperationRequest = Operation["request"];
export type OperationResponses = httpApiRuntime.ExtractResponses<Operation["responses"]>;
export type Event = httpApiRuntime.EventType<Operation>;
export type Handler = httpApiRuntime.LambdaHandler<Operation>;

export const entrypoint = httpApiRuntime.wrapper<Operation>(handler, validators);
