openapi: 3.0.1
info:
  title: SDF Example - Authorizer
  version: 0.0.1

paths:
  /testing:
    get:
      operationId: testing
      description: testing
      responses:
        "200":
          description: "testing"
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Response" }
      security:
        - authorizer: []

components:
  schemas:
    Response:
      type: "object"
      properties:
        ok:
          description: indicates the status
          type: boolean
        user:
          description: indicates the username
          type: string
      required:
        - ok
        - user

  securitySchemes:
    authorizer:
      type: "apiKey"
      name: "ApiKey"
      in: "header"
