openapi: 3.0.1
info:
  title: SDF Example - Authorizer
  version: 0.0.1

paths:
  /identity:
    get:
      operationId: identity/me
      description: Get current user
      responses:
        "200":
          description: Current user
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Response" }
      security:
        - authorizer: []

  /item:
    post:
      operationId: item/create
      description: Create a new item
      requestBody:
        required: true
        description: The item body
        content:
          application/json:
            schema: { $ref: "#/components/schemas/ItemCreateRequest" }
      responses:
        "201":
          description: Item created
      security:
        - authorizer: []

  /item/{itemId}:
    parameters:
      - in: path
        name: itemId
        schema:
          type: string
        required: true
        description: The item ID
    get:
      operationId: item/get
      description: Create a new item
      responses:
        "200":
          description: Created item
          content:
            application/json:
              schema: { $ref: "#/components/schemas/ItemGetResponse" }

      security:
        - authorizer: []

components:
  schemas:
    Response:
      title: Response
      type: "object"
      properties:
        ok:
          description: indicates the status
          type: boolean
        user:
          description: indicates the username
          type: string
      required:
        - ok
        - user

    BaseItem:
      title: BaseItem
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
      required:
        - name

    Item:
      title: Item
      allOf:
        - $ref: "#/components/schemas/BaseItem"
        - type: object
          additionalProperties: false
          properties:
            id:
              type: string
            created:
              type: string
              format: date-time
          required:
            - id
            - created

    ItemCreateRequest:
      title: ItemCreateRequest
      type: object
      properties:
        item: { $ref: "#/components/schemas/BaseItem" }
      required:
        - item

    ItemCreateResponse:
      title: ItemCreateResponse
      type: object
      properties:
        item: { $ref: "#/components/schemas/Item" }
      required:
        - item

    ItemGetResponse:
      title: ItemGetResponse
      type: object
      properties:
        item: { $ref: "#/components/schemas/Item" }
      required:
        - item

  securitySchemes:
    authorizer:
      type: "apiKey"
      name: "ApiKey"
      in: "header"
