/**
 * ATTENTION: This file was generated by @cloudventure/sdf package
 * and it will be regenerated when the stack is synthesized.
 */

import { httpApiRuntime } from "@cloudventure/sdf";
import { {{ AuthorizerModel }} as AuthorizerContext } from "./{{ InterfacesImport }}";
import { authorizer } from "./{{ HandlerImport }}";

export { AuthorizerContext }

export const {{ EntryPointFunctionName }} = httpApiRuntime.authorizerWrapper<AuthorizerContext>(authorizer);
