/**
 * ATTENTION: This file was generated by @cloudventure/sdf package
 * and it will be regenerated when the stack is synthesized.
 */

import { httpApiRuntime } from "@cloudventure/sdf";
import { AuthContext as AuthorizerContext } from "./../interfaces";
import { authorizer } from "./../authorizers/authorizer";

export { AuthorizerContext }

export const entrypoint = httpApiRuntime.authorizerWrapper<AuthorizerContext>(authorizer);
