---
name: Release

concurrency: release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Run Tests
        run: yarn test

  publish:
    needs: [tests]
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code

      - run: jq -r '"version=v" + .version' package.json >> $GITHUB_OUTPUT
        id: package-json

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Add README
        run: cp README.md dist/README.md

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPMJS_TOKEN }}
          access: public
          check-version: true
          package: dist/package.json

      - name: Tag
        if: steps.publish.outputs.type != 'none'
        run: |
          git tag v${{ steps.publish.outputs.version }}
          git push --tags
