---
name: Release

concurrency: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code

      - name: Install and build
        uses: ./.github/actions/install-and-build

      - name: Run Tests
        run: pnpm test

  e2e-tests:
    name: End-to-end tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        example: [api-lambda-auth]
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code

      - name: Install and build
        uses: ./.github/actions/install-and-build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Install example
        run: |
          cd examples/${{ matrix.example }}
          pnpm install
          pnpm synth
          pnpm build

      - name: Deploy the example
        run: |
          cd cdktf.out/stacks/deployment
          terraform init
          terraform plan

  # publish:
  #   needs: [tests, e2e-tests]
  #   name: Publish
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       name: Checkout the code

  #     - name: Install and build
  #       uses: ./.github/actions/install-and-build

  #     - name: Publish
  #       uses: JS-DevTools/npm-publish@v1
  #       id: publish
  #       with:
  #         token: ${{ secrets.NPMJS_TOKEN }}
  #         access: public
  #         check-version: true
  #         package: dist/package.json

  #     - name: Tag
  #       if: steps.publish.outputs.type != 'none'
  #       run: |
  #         git tag v${{ steps.publish.outputs.version }}
  #         git push --tags
